name: Rust

on:
  push:
    branches: [ '*' ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo build
    - run: cargo test
    - uses: actions-rs/clippy-check@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: zkutil
        path: target/debug/zkutil
    - name: Publish on crates.io
      if: startsWith(github.ref, 'refs/tags')
      run: |
        [ ${GITHUB_REF#refs/tags/v} = $(grep "^version" Cargo.toml | grep -o "[0-9.]*") ] || (echo "Git tag doesn't match version in Cargo.toml" && false)
        cargo publish --token $CRATES_IO_TOKEN
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
